version: '3.4'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.40.0
    ports:
      - '16686:16686'
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.68.0
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./docker-compose-otel/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - '4317:4317'
      - '4318:4318'
      - '8888:8888'
      - '9999:9999'
    depends_on:
      - jaeger
      - prometheus

  prometheus:
    image: prom/prometheus:v2.41.0
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    volumes:
      - ./docker-compose-otel/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:9.3.2
    ports:
      - '3001:3000'
    volumes:
      - ./docker-compose-otel/ds-prometheus.yaml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    depends_on:
      - prometheus